In [25]:
import numpy as np

# Step 1: Take input for number of rows and columns
m = int(input("Enter number of rows: "))
n = int(input("Enter number of columns: "))

# Step 2: Initialize an empty matrix with zeros
U = np.zeros((m, n))

# Step 3: Take input for each element
print("Enter the elements row by row:")
for i in range(m):
    for j in range(n):
        U[i, j] = float(input(f"Element at row {i+1}, column {j+1}: "))

# Step 4: Print the final matrix
print("\nThe matrix U is:")
print(U)

 



Enter number of rows:  2
Enter number of columns:  2


Enter the elements row by row:


Element at row 1, column 1:  1
Element at row 1, column 2:  2
Element at row 2, column 1:  4
Element at row 2, column 2:  6



The matrix U is:
[[1. 2.]
 [4. 6.]]


In [26]:
X=U.T
print(x)

[[1. 3.]
 [2. 4.]]


In [27]:
m=2
Y=np.random.random((1,m))
print(y)

[[0.06352539 0.46629916]]


In [28]:
p=3
n=2
W1=np.random.random((p,n))
print(W1)

[[0.65288541 0.56803214]
 [0.97114135 0.6087056 ]
 [0.71152809 0.72190136]]


In [29]:
B1=np.random.random((p,1))
print(B1)

[[0.49703566]
 [0.71133319]
 [0.17505956]]


In [30]:
W2=np.random.random((1,p))
print(W2)

[[0.79392973 0.29557185 0.42653279]]


In [31]:
B2=np.random.rand()
print(B2)

0.9049742597896147


In [39]:
Z1 = np.dot(W1, X) + B1
print("Z1:\n", Z1)


Z1:
 [[2.28430491 6.51200702]
 [2.89926085 8.24636097]
 [2.32948796 7.35002224]]


In [40]:
def f(Z1):
    return np.maximum(0, Z1)  # ReLU

A1 = f(Z1)
print("A1:\n", A1)


A1:
 [[2.28430491 6.51200702]
 [2.89926085 8.24636097]
 [2.32948796 7.35002224]]


In [41]:
Z2 = np.dot(W2, A1) + B2
print("Z2:\n", Z2)


Z2:
 [[ 4.56201675 11.62737751]]


In [42]:
def g(Z2):
    return 1 / (1 + np.exp(-Z2))  # Sigmoid

A2 = g(Z2)
print("A2:\n", A2)


A2:
 [[0.98966691 0.99999108]]


In [43]:
L = 0.5 * np.square(A2 - Y)
print("Loss L:\n", L)


Loss L:
 [[0.10601315 0.27593616]]


In [44]:
dA2 = A2 - Y
print("dA2:\n", dA2)


dA2:
 [[0.46046313 0.7428811 ]]


In [45]:
def gprime(Z2):
    gz2 = g(Z2)
    return gz2 * (1 - gz2)

dZ2 = dA2 * gprime(Z2)  # element-wise multiplication
print("dZ2:\n", dZ2)


dZ2:
 [[4.70884353e-03 6.62530188e-06]]


In [46]:
dA1 = np.dot(W2.T, dZ2)
print("dA1:\n", dA1)


dA1:
 [[3.73469295e-03 5.25468048e-06]
 [1.38698263e-03 1.95147249e-06]
 [2.00460220e-03 2.82045786e-06]]


In [47]:
def fprime(Z1):
    return (Z1 > 0).astype(float)  # derivative of ReLU

dZ1 = dA1 * fprime(Z1)
print("dZ1:\n", dZ1)


dZ1:
 [[3.73469295e-03 5.25468048e-06]
 [1.38698263e-03 1.95147249e-06]
 [2.00460220e-03 2.82045786e-06]]


In [48]:
m = X.shape[1]  # number of samples
dW1 = (1/m) * np.dot(dZ1, X.T)
print("dW1:\n", dW1)


dW1:
 [[0.00187786 0.00375046]
 [0.00069739 0.00139284]
 [0.00100794 0.00201306]]


In [49]:
dB1 = (1/m) * np.sum(dZ1, axis=1, keepdims=True)
print("dB1:\n", dB1)


dB1:
 [[0.00186997]
 [0.00069447]
 [0.00100371]]


In [50]:
dW2 = (1/m) * np.dot(dZ2, A1.T)
print("dW2:\n", dW2)


dW2:
 [[0.00539979 0.0068534  0.00550895]]
