In [2]:
# ---------------------------------------------------
# Step 1: Import required libraries
# ---------------------------------------------------
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

# ---------------------------------------------------
# Step 2: Create DataFrame with random data
# ---------------------------------------------------
np.random.seed(42)  # for reproducibility
df = pd.DataFrame({
    "EmployeeID": np.arange(101, 151),
    "Experience": np.random.randint(1, 21, size=50),
    "TrainingHours": np.random.randint(10, 101, size=50).astype(float),
    "PerformanceScore": np.random.randint(50, 101, size=50),
    "Promotion": np.random.randint(0, 2, size=50)
})
print("Original DataFrame:")
print(df.head())

# ---------------------------------------------------
# Step 3: Handle missing values
# ---------------------------------------------------
df["TrainingHours"].fillna(df["TrainingHours"].mean(), inplace=True)

# ---------------------------------------------------
# Step 4: Update TrainingHours for employees with Experience > 10
# ---------------------------------------------------
df.loc[df["Experience"] > 10, "TrainingHours"] += 10

# ---------------------------------------------------
# Step 5: Split the dataset
# ---------------------------------------------------
X = df[["Experience", "TrainingHours", "PerformanceScore"]]
y = df["Promotion"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# ---------------------------------------------------
# Step 6: Build Logistic Regression model
# ---------------------------------------------------
model = LogisticRegression()
model.fit(X_train, y_train)

# ---------------------------------------------------
# Step 7: Evaluate the model
# ---------------------------------------------------
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print("\nAccuracy:", accuracy)
print("\nConfusion Matrix:\n", cm)


Original DataFrame:
   EmployeeID  Experience  TrainingHours  PerformanceScore  Promotion
0         101           7           13.0                77          0
1         102          20           11.0                56          1
2         103          15           15.0                58          0
3         104          11           63.0                57          0
4         105           8           13.0                61          0

Accuracy: 0.5333333333333333

Confusion Matrix:
 [[5 4]
 [3 3]]


/tmp/ipykernel_10065/3521603964.py:27: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["TrainingHours"].fillna(df["TrainingHours"].mean(), inplace=True)


In [6]:
# Step 1: Import required libraries
# ---------------------------------------------------
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

# ---------------------------------------------------
# Step 2: Create DataFrame in ONE step with random data
# ---------------------------------------------------
np.random.seed(42)  # for reproducibility

df = pd.DataFrame({
    "EmployeeID": np.arange(101, 151),
    "Experience": np.random.randint(1, 21, size=50),
    "TrainingHours": np.random.randint(10, 101, size=50).astype(float),
    "PerformanceScore": np.random.randint(50, 101, size=50),
    "Promotion": np.random.randint(0, 2, size=50)
})

# Insert NaN values randomly into TrainingHours
df.loc[np.random.choice(df.index, 5, replace=False), "TrainingHours"] = np.nan

print("Original DataFrame:")
print(df)

Original DataFrame:
    EmployeeID  Experience  TrainingHours  PerformanceScore  Promotion
0          101           7           13.0                77          0
1          102          20           11.0                56          1
2          103          15           15.0                58          0
3          104          11           63.0                57          0
4          105           8           13.0                61          0
5          106           7           63.0                83          1
6          107          19            NaN                82          1
7          108          11           27.0                97          1
8          109          11           99.0                72          1
9          110           4            NaN                73          0
10         111           8           43.0                86          1
11         112           3           83.0                84          0
12         113           2           71.0                

In [7]:
df["TrainingHours"].fillna(df["TrainingHours"].mean(), inplace=True)
print(df)

    EmployeeID  Experience  TrainingHours  PerformanceScore  Promotion
0          101           7      13.000000                77          0
1          102          20      11.000000                56          1
2          103          15      15.000000                58          0
3          104          11      63.000000                57          0
4          105           8      13.000000                61          0
5          106           7      63.000000                83          1
6          107          19      54.711111                82          1
7          108          11      27.000000                97          1
8          109          11      99.000000                72          1
9          110           4      54.711111                73          0
10         111           8      43.000000                86          1
11         112           3      83.000000                84          0
12         113           2      71.000000                93          0
13    

/tmp/ipykernel_10065/2167002524.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["TrainingHours"].fillna(df["TrainingHours"].mean(), inplace=True)


In [9]:
# Step 4: Update TrainingHours for employees with Experience > 10
# ---------------------------------------------------
df.loc[df["Experience"] > 10, "TrainingHours"] += 10
print(df)

    EmployeeID  Experience  TrainingHours  PerformanceScore  Promotion
0          101           7      13.000000                77          0
1          102          20      31.000000                56          1
2          103          15      35.000000                58          0
3          104          11      83.000000                57          0
4          105           8      13.000000                61          0
5          106           7      63.000000                83          1
6          107          19      74.711111                82          1
7          108          11      47.000000                97          1
8          109          11     119.000000                72          1
9          110           4      54.711111                73          0
10         111           8      43.000000                86          1
11         112           3      83.000000                84          0
12         113           2      71.000000                93          0
13    

In [10]:
# Step 5: Split the dataset
# ---------------------------------------------------
X = df[["Experience", "TrainingHours", "PerformanceScore"]]
y = df["Promotion"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# ---------------------------------------------------
# Step 6: Build Logistic Regression model
# ---------------------------------------------------
model = LogisticRegression()
model.fit(X_train, y_train)

# ---------------------------------------------------
# Step 7: Evaluate the model
# ---------------------------------------------------
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print("\nAccuracy:", accuracy)
print("\nConfusion Matrix:\n", cm)


Accuracy: 0.5333333333333333

Confusion Matrix:
 [[5 4]
 [3 3]]


In [12]:
import tensorflow as tf

# 1. Create random 3x3 matrix A
A = tf.random.uniform((3, 3), minval=0, maxval=5, dtype=tf.float32)
I = tf.eye(3)

# Compute P = I + A + (A^2)/2! + (A^3)/3!
P = I + A + tf.matmul(A, A)/2.0 + tf.matmul(tf.matmul(A, A), A)/6.0

print("Matrix A:\n", A.numpy())
print("\nMatrix P:\n", P.numpy())

# 2. Create random 3x1 vector b
b = tf.random.uniform((3, 1), minval=0, maxval=5, dtype=tf.float32)

# Compute z = P * b
z = tf.matmul(P, b)
print("\nVector b:\n", b.numpy())
print("\nResult z:\n", z.numpy())

# 3. Compute gradient of L = ||z||^2 with respect to A and b
with tf.GradientTape(persistent=True) as tape:
    tape.watch(A)
    tape.watch(b)
    P = I + A + tf.matmul(A, A)/2.0 + tf.matmul(tf.matmul(A, A), A)/6.0
    z = tf.matmul(P, b)
    L = tf.reduce_sum(tf.square(z))  # ||z||^2

# Gradients
dL_dA = tape.gradient(L, A)
dL_db = tape.gradient(L, b)

print("\nGradient dL/dA:\n", dL_dA.numpy())
print("\nGradient dL/db:\n", dL_db.numpy())


Matrix A:
 [[1.6726148 0.2436173 0.9218234]
 [3.031236  4.770599  3.8679857]
 [4.46649   1.3458735 3.6503272]]

Matrix P:
 [[14.40683   5.506063 10.39249 ]
 [72.523636 52.371277 67.22624 ]
 [49.29374  23.644308 42.040386]]

Vector b:
 [[0.32323837]
 [3.7380338 ]
 [4.9181323 ]]

Result z:
 [[ 76.35033]
 [549.8356 ]
 [311.07703]]

Gradient dL/dA:
 [[ 12126.649  99716.09   96784.78 ]
 [ 20531.684 153420.17  121942.805]
 [ 17019.885 132543.8   115644.3  ]]

Gradient dL/db:
 [[112620.375]
 [ 73142.36 ]
 [101669.29 ]]


In [15]:
# ---------------------------------------------------
# Step 1: Import necessary libraries
# ---------------------------------------------------
import tensorflow as tf
import math  # use math.factorial instead of tf.math.factorial

# ---------------------------------------------------
# Step 2: Create random 4x4 matrix M and 4x1 vector v
# ---------------------------------------------------
M = tf.random.normal((4, 4))   # Random 4x4 matrix
v = tf.random.normal((4, 1))   # Random 4x1 vector

# ---------------------------------------------------
# Step 3: Define a custom matrix_power function
# ---------------------------------------------------
def matrix_power(M, n):
    """Computes M^n manually using tf.matmul."""
    result = tf.eye(M.shape[0], dtype=M.dtype)
    for _ in range(n):
        result = tf.matmul(result, M)
    return result

# ---------------------------------------------------
# Step 4: Compute Q = I + M + M^2/2! + M^3/3! + M^4/4! + M^5/5!
# ---------------------------------------------------
I = tf.eye(4)
Q = I
for i in range(1, 6):
    Q += matrix_power(M, i) / tf.cast(math.factorial(i), tf.float32)

print("Matrix Q:\n", Q.numpy())

# ---------------------------------------------------
# Step 5: Compute y = Q × v
# ---------------------------------------------------
y = tf.matmul(Q, v)
print("\nVector y:\n", y.numpy())

# ---------------------------------------------------
# Step 6: Compute gradient of ||y||^2 with respect to M and v
# ---------------------------------------------------
with tf.GradientTape(persistent=True) as tape:
    tape.watch([M, v])
    Q = I
    for i in range(1, 6):
        Q += matrix_power(M, i) / tf.cast(math.factorial(i), tf.float32)
    y = tf.matmul(Q, v)
    loss = tf.reduce_sum(tf.square(y))  # ||y||^2

# Gradients
grad_M = tape.gradient(loss, M)
grad_v = tape.gradient(loss, v)

print("\nGradient with respect to M:\n", grad_M.numpy())
print("\nGradient with respect to v:\n", grad_v.numpy())


Matrix Q:
 [[  1.1951334    2.8032434   -0.17460287   1.9789963 ]
 [ -3.4240177    9.313686    -0.3005691  -10.344841  ]
 [ -1.2543564   -3.856192     1.1351622   -1.9224466 ]
 [  0.73116463   1.6389      -0.42793918   1.9774394 ]]

Vector y:
 [[-0.7942431 ]
 [-6.960508  ]
 [ 1.1212618 ]
 [-0.03157473]]

Gradient with respect to M:
 [[-3.5917182e+00 -6.8586826e+00 -1.7043331e+00  4.8397393e+00]
 [ 1.8480026e+01  8.1223534e+01  3.2908733e+00 -2.4511894e+01]
 [-1.3588448e+00 -8.1083117e+00  3.6407560e-02  1.7528914e+00]
 [-1.2845505e+01 -3.4949974e+01 -4.7611332e+00  1.7107059e+01]]

Gradient with respect to v:
 [[  42.908253 ]
 [-142.85999  ]
 [   7.0342336]
 [ 136.43108  ]]
