In [5]:
# Step 1: Import required libraries
# ---------------------------------------------------
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

import pandas as pd
import numpy as np

df = pd.DataFrame({
    "EmployeeID": range(200, 241),
    "SalesScore": np.random.randint(50, 201, size=41),
    "CustomerRating": np.random.randint(1, 11, size=41)
})

print(df)
# Read first 5 rows
print(df.head())



    EmployeeID  SalesScore  CustomerRating
0          200         105               1
1          201         105               1
2          202         163               5
3          203         102               7
4          204         187               9
5          205          87               2
6          206          84               1
7          207         151               5
8          208         114               2
9          209          77               1
10         210         131               4
11         211         105               9
12         212         119               7
13         213          73               6
14         214         157               3
15         215         125               3
16         216         126               8
17         217         195               4
18         218         126               1
19         219          75              10
20         220          71               4
21         221          70               7
22         

In [4]:
# Filter
print(df[df['SalesScore'] > 150])


    EmployeeID  SalesScore  CustomerRating
3          203         171               2
4          204         180               2
10         210         179               1
13         213         182               1
14         214         199               8
15         215         161              10
23         223         193               9
26         226         176               9
27         227         168               5
28         228         167               5
30         230         183               4
31         231         161               3
36         236         198               2
40         240         186               2


In [6]:
filtered = df[(df["SalesScore"] >= 150) | (df["CustomerRating"] > 8)]
print(df)

    EmployeeID  SalesScore  CustomerRating
0          200         105               1
1          201         105               1
2          202         163               5
3          203         102               7
4          204         187               9
5          205          87               2
6          206          84               1
7          207         151               5
8          208         114               2
9          209          77               1
10         210         131               4
11         211         105               9
12         212         119               7
13         213          73               6
14         214         157               3
15         215         125               3
16         216         126               8
17         217         195               4
18         218         126               1
19         219          75              10
20         220          71               4
21         221          70               7
22         

In [11]:
df["SalesScoreNorm"] = (df["SalesScore"] - df["SalesScore"].min()) / (
                        df["SalesScore"].max() - df["SalesScore"].min())


In [12]:
df["Status"] = np.where(
    (df["SalesScore"] >= 120) & (df["CustomerRating"] >= 7),
    "Promoted", "Retain"
)
print(df.head)

<bound method NDFrame.head of     EmployeeID  SalesScore  CustomerRating  SalesScoreNorm    Status
0          200         105               1        0.333333    Retain
1          201         105               1        0.333333    Retain
2          202         163               5        0.762963    Retain
3          203         102               7        0.311111    Retain
4          204         187               9        0.940741  Promoted
5          205          87               2        0.200000    Retain
6          206          84               1        0.177778    Retain
7          207         151               5        0.674074    Retain
8          208         114               2        0.400000    Retain
9          209          77               1        0.125926    Retain
10         210         131               4        0.525926    Retain
11         211         105               9        0.333333    Retain
12         212         119               7        0.437037    Retain
13  

In [13]:
X = df[["SalesScoreNorm", "CustomerRating"]]
y = df["Status"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[ 2  0]
 [ 1 10]]
              precision    recall  f1-score   support

    Promoted       0.67      1.00      0.80         2
      Retain       1.00      0.91      0.95        11

    accuracy                           0.92        13
   macro avg       0.83      0.95      0.88        13
weighted avg       0.95      0.92      0.93        13



In [15]:
import tensorflow as tf

tf.random.set_seed(42)  # for reproducibility

W1 = tf.random.normal((6, 4))   # Matrix 1
W2 = tf.random.normal((2, 4))   # Matrix 2
b1 = tf.random.normal((4, 1))   # Bias 1
W3 = tf.random.normal((2, 2))   # Matrix 3 (not directly used later)
b2 = tf.random.normal((2, 1))   # Bias 2

# Input vector
X = tf.random.normal((6, 1))
Z1 = tf.matmul(tf.transpose(W1), X) + b1   # Linear combination for layer 1
A1 = tf.nn.tanh(Z1)                        # Activation for layer 1
Z2 = tf.matmul(W2, A1) + b2                # Linear combination for layer 2
A2 = tf.nn.sigmoid(Z2)                     # Activation for output layer
print("Z1:\n", Z1.numpy())
print("A1:\n", A1.numpy())
print("Z2:\n", Z2.numpy())
print("A2:\n", A2.numpy())


Z1:
 [[ 0.73039645]
 [ 0.2019254 ]
 [-1.314518  ]
 [-1.5326632 ]]
A1:
 [[ 0.6233078 ]
 [ 0.199225  ]
 [-0.86541414]
 [-0.91087914]]
Z2:
 [[-0.43226904]
 [-0.5596659 ]]
A2:
 [[0.39358464]
 [0.36362475]]


In [16]:
import tensorflow as tf

# Step 1: Create tensors
tf.random.set_seed(10)
A = tf.random.normal((3, 2))
B = tf.random.normal((2, 3))
b = tf.random.normal((3, 1))

# Step 2: Forward computation
Z = tf.matmul(A, B) + b
A_relu = tf.nn.relu(Z)

print("Z:\n", Z.numpy())
print("\nActivated Output (ReLU):\n", A_relu.numpy())

# Step 3: Compute gradients
with tf.GradientTape() as tape:
    tape.watch([A, B])
    Z = tf.matmul(A, B) + b
    A_relu = tf.nn.relu(Z)

grads = tape.gradient(A_relu, [A, B])

print("\nGradient wrt A:\n", grads[0].numpy())
print("\nGradient wrt B:\n", grads[1].numpy())


Z:
 [[-0.9248416   0.09371817  1.1959927 ]
 [-1.5455334  -0.80186665 -0.7425548 ]
 [-0.2093615  -0.88885844 -0.00704423]]

Activated Output (ReLU):
 [[0.         0.09371817 1.1959927 ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]

Gradient wrt A:
 [[-2.8668652 -1.7833151]
 [ 0.         0.       ]
 [ 0.         0.       ]]

Gradient wrt B:
 [[ 0.        -0.8757808 -0.8757808]
 [ 0.         0.3356369  0.3356369]]
