In [2]:
import tensorflow as tf
import numpy as np
# define shape
m = 2  # number of examples (rows)
n = 3  # input features (columns)

# create matrix U
U = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)
print("Matrix U:")
print(U)


Matrix U:
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


In [3]:
X = tf.transpose(U)
print("Matrix X (Transpose of U):")
print(X)


Matrix X (Transpose of U):
tf.Tensor(
[[1. 4.]
 [2. 5.]
 [3. 6.]], shape=(3, 2), dtype=float32)


In [8]:
Y = tf.random.uniform(shape=(1, m), minval=0, maxval=10, dtype=tf.int32)
print("Matrix Y:")
print(Y.numpy())


Matrix Y:
[[0 6]]


In [23]:
p = 3  # number of hidden layer units
W1 = tf.Variable(tf.random.uniform(shape=(p, n), minval=0, maxval=10))
print("Matrix W1:")
print(W1.numpy())


Matrix W1:
[[1.3010275  0.62790036 6.7164316 ]
 [1.0118222  3.1084597  1.9225252 ]
 [2.4345505  8.503208   2.807436  ]]


In [10]:
B1 = tf.Variable(tf.random.uniform((p, 1), 0, 1))#shape minval maxval
print("Vector B1:")
print(B1.numpy())


Vector B1:
[[0.7195667 ]
 [0.13529074]
 [0.29145968]]


In [11]:
W2 = tf.Variable(tf.zeros((1, p)), dtype=tf.float32)
print("Vector W2:")
print(W2.numpy())


Vector W2:
[[0. 0. 0.]]


In [12]:
B2 = tf.Variable(tf.random.uniform((1, 1), 0, 1))
print("Scalar B2:")
print(B2.numpy())


Scalar B2:
[[0.03985071]]


In [17]:
def relu(z):
    return tf.maximum(0.0, z)

def relu_prime(z):
    return tf.cast(z > 0, tf.float32)

def sigmoid(z):
    return 1 / (1 + tf.exp(-z))

def sigmoid_prime(z):
    g = sigmoid(z)
    return g * (1 - g)


In [22]:
alpha = tf.constant(0.01)  # learning rate
num_iters = 15             # number of iterations

for i in range(num_iters):
    # Forward pass
    Z1 = tf.matmul(W1, X) + B1
    A1 = relu(Z1)
    Z2 = tf.matmul(W2, A1) + B2
    A2 = sigmoid(Z2)

    # Compute loss (L)
    L = 0.5 * tf.reduce_mean((A2 - tf.cast(Y, tf.float32)) ** 2)

        # Backward pass (gradients)
        # Backward pass (gradients)
    dA2 = A2 - tf.cast(Y, tf.float32)
    dZ2 = dA2 * sigmoid_prime(Z2)
    dA1 = tf.matmul(tf.transpose(W2), dZ2)
    dZ1 = dA1 * relu_prime(Z1)
    
    dW1 = (1 / m) * tf.matmul(dZ1, tf.transpose(X))
    dB1 = (1 / m) * tf.reduce_sum(dZ1, axis=1, keepdims=True)
    
    dW2 = (1 / m) * tf.matmul(dZ2, tf.transpose(A1))
    dB2 = (1 / m) * tf.reduce_sum(dZ2, axis=1, keepdims=True)  # ✅ FIXED

    # Parameter update
    W1.assign_sub(alpha * dW1)
    B1.assign_sub(alpha * dB1)
    W2.assign_sub(alpha * dW2)
    B2.assign_sub(alpha * dB2)

    # Parameter update
    W1.assign_sub(alpha * dW1)
    B1.assign_sub(alpha * dB1)
    W2.assign_sub(alpha * dW2)
    B2.assign_sub(alpha * dB2)

    # Display
    print(f"\nIteration {i + 1}")
    print("Loss:", L.numpy())
    print("W1:\n", W1.numpy())
    print("B1:\n", B1.numpy())
    print("W2:\n", W2.numpy())
    print("B2:\n", B2.numpy())
    
print("B2 shape:", B2.shape)
print("dB2 shape:", dB2.shape)



Iteration 1
Loss: 0.09553456
W1:
 [[0.3149459  0.6656     0.05075102]
 [0.48578256 0.38802722 0.9142785 ]
 [0.5141316  0.9878936  0.2156306 ]]
B1:
 [[0.22904338]
 [0.7743113 ]
 [0.3597662 ]]
W2:
 [[-0.0347003  -0.05254214 -0.05707176]]
B2:
 [[0.36230505]]

Iteration 2
Loss: 0.09545737
W1:
 [[0.31498733 0.6656169  0.0507434 ]
 [0.48584533 0.38805285 0.91426694]
 [0.5141998  0.98792136 0.21561809]]
B1:
 [[0.22901885]
 [0.7742741 ]
 [0.35972583]]
W2:
 [[-0.03522774 -0.05256335 -0.05786554]]
B2:
 [[0.3630119]]

Iteration 3
Loss: 0.09538771
W1:
 [[0.31502846 0.6656329  0.05073416]
 [0.48590666 0.38807663 0.9142531 ]
 [0.5142674  0.9879476  0.21560292]]
B1:
 [[0.22899367]
 [0.77423656]
 [0.35968447]]
W2:
 [[-0.03571955 -0.05251268 -0.05859901]]
B2:
 [[0.36372674]]

Iteration 4
Loss: 0.09532334
W1:
 [[0.31506935 0.66564804 0.05072351]
 [0.4859668  0.38809887 0.9142375 ]
 [0.5143345  0.9879724  0.21558546]]
B1:
 [[0.22896789]
 [0.77419865]
 [0.3596422 ]]
W2:
 [[-0.03618163 -0.05240211 -0.0592